name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install FPC
        run: |
          sudo apt update
          sudo apt install -y fpc
          sudo apt install -y make

      - name: Build
        run: make

      - name: Package with nfpm
        uses: goreleaser/nfpm@v2.46.3
        with:
          args: package --config nfpm.yaml --target .
        env:
          VERSION: ${{ github.ref_name }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
