name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install FPC
        run: |
          sudo apt update
          sudo apt install -y fpc
          sudo apt install -y make

      - name: Build
        run: make

      - name: Package with nfpm
        run: |
          echo "Installing nfpm..."
          curl -sfL https://github.com/goreleaser/nfpm/releases/download/v2.46.3/nfpm_2.46.3_Linux_x86_64.tar.gz | tar -xz nfpm
          sudo mv nfpm /usr/local/bin/

          nfpm package --config nfpm.yaml --target .
        env:
          VERSION: ${{ github.ref_name }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
